### PR TITLE
Enable clippy, fmt and doc in CI

### PR DESCRIPTION
**Pull request by francocipollone**
# 🎉 New feature

Related to #16 
Closes https://github.com/maliput/maliput-rs/issues/21

## Summary
What the title says

## Pendings
 - [ ] Fix all clippy errors
 - [ ] Fix all fmt errors

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)

### CODE REVIEW

**Comment by agalbachicar** [comment]
@francocipollone for my own understanding: does cargo build already take care of formatting the code and making sure all the other checks will pass? If not, can we set at least write in the readme what should be run to make things compliant with the checks we will expect in CI to pass? A precommit / script would be great too.

**Comment by francocipollone** [comment]
> @francocipollone for my own understanding: does cargo build already take care of formatting the code and making sure all the other checks will pass? If not, can we set at least write in the readme what should be run to make things compliant with the checks we will expect in CI to pass? A precommit / script would be great too.

Yeah, I was thinking about having a precommit for this. We can add this to this PR so it is all added together.

**Comment by francocipollone** [comment]
For some reason the `cargo clippy` execution is failing in CI. It complains about the `build.rs`'s execution of the bazel module:

> ERROR: Skipping '//...': error loading package under directory '': error loading package 'bazel-maliput-sdk/external/yaml-cpp~0.8.0/test/gtest-1.11.0/googletest/test': Unable to find package for @[unknown repo 'rules_python' requested from @]//python:defs.bzl: The repository '@[unknown repo 'rules_python' requested from @]' could not be resolved: No repository visible as '@rules_python' from main repository.

It works correctly locally.

**Comment by francocipollone** [comment]
I was able to replicate it locally:

```
docker pull ghcr.io/maliput/maliput-rs-rust-ci:rust1.75.0
docker run -it ghcr.io/maliput/maliput-rs-rust-ci:rust1.75.0 bash
git clone https://github.com/maliput/maliput-rs.git
cd maliput-rs
pre-commit run --all-files --verbose --show-diff-on-failure
```

**Comment by francocipollone** [comment]
Bug fixed at https://github.com/maliput/maliput-rs/pull/26

**Comment by francocipollone** [comment]
Alrighty, bugs are solved. Ready for another pass @agalbachicar :D

**Comment by francocipollone** [comment]
friendly ping @agalbachicar :smile:

**Review by agalbachicar — APPROVED** [review]
LGTM

**Pull request merged**
